- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: check secret file
      include_vars: "/var/lib/awx/projects/secret.txt"
